### ISSUE TITLE
无法通过CatAntiCheat客户端验证

### ISSUE THREAD

**Issue by Bliod-Cook** [SerendipityR-2022/EndMinecraftPlusV2#8]
已知服务器添加了CatAntiCheat 不知道是不是这个插件导致的
配置如下
```
##############################
#  EndMinecraftPlusV2        #
#    Forked by SerendipityR  #
##############################

CfgVer: 3

AttackSettings:
  Address: "server.com"
  Port: 25565
  # 攻击方式:
  # 1 - BotAttack - 集群假人(代理)
  # 2 - MotdAttack - MOTD压测(无代理)
  # 3 - MotdAttackP - MOTD压测(代理)
  # 4 - DoubleAttack - 影分身攻击(代理，仅原版单服可用)
  Method: 1
  Time: 3600
  ConnectDelay: 25
  ConnectTimeout: 16000
  # 实际连接数由代理质量和机器性能有关
  # 进行无代理Motd压测时不建议大于32
  MaxConnections: 2000
  # 旧版漏洞利用，大概率无效
  TabAttack: false
  AntiAttackMode: true
  DoubleExploitPlayer: "ImOldSix_666"
  ShowFails: false

BotSettings:
  # 可用占位符:
  # $rnd - 随机字符
  # $pwd - 随机生成密码
  BotName: "NoMoney_$rnd"
  BotCount: 1000
  # 随机字符规则 (仅影响BotName):
  # 1 - Normal - 简单随机化
  # 2 - Ili - iii混淆式
  # 3 - ABC - 纯字母
  # 4 - 123 - 纯数字
  RandomFlag: 1
  RandomMinLength: 4
  RandomMaxLength: 6
  # 尝试发送随机传送数据包
  RandomTeleport: false
  RejoinCount: 5
  RejoinDelay: 5000
  RejoinDetect:
    - "重"
    - "压"
  ClickVerifiesDetect:
    - "点"
  Register&Login: true
  RegisterCommands:
    - "/register $pwd $pwd"
    - "/login $pwd"
    - "Message"
  ChatSpam: true
  CustomChat:
    - "Message"
  ChatDelay: 3000

Proxy:
  # 代理获取方式:
  # 1 - API - 从API获取
  # 2 - File - 从本地读取
  # 3 - File + API - 两种方式同时获取
  GetType: 2
  # 代理类型:
  # 1 - HTTP/HTTPS
  # 2 - SOCKS4
  # 3 - SOCKS5
  ProxyType: 1
  UpdateTime: 300
  File: "wp2.txt"
  APIs:
    - "http://api.fulucdn.com/api/http.txt"
  # 保存能连接到目标服务器的代理地址 (如果支持)
  # 位置: working-proxies.txt
  SaveWorkingProxy: true
```
